# Generated by Django 3.1.3 on 2020-11-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippettest',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
