# Generated by Django 3.1.3 on 2020-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet_test', '0002_snippettest_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippettest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
